---
version: "3.8"
services:
  movies:
    image: suresh7625/paymovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: suresh7625/paytrain:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: suresh7625/paydth:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: suresh7625/payrecharge:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
